### PR TITLE
automatically nest httpkey (disableNesting flag added to config)

### PR DESCRIPTION
**Pull request by orokos**
I discussed this feature with you after the Derbycon talk, here's the PR. First time actually working in Go, I feel like it would be better to change the `Run` calls to use streams instead of writing to disk so that they can be chained without writing the result file multiple times but I'm not familiar with Go I/O enough to feel like I should be the one to do that.

`golint` picked up a broken comment and `GenerateHttpKey` to `GenerateHTTPKey`, two of the files were CRLF and so there is noise making em LF.

Lemme know if there is a better/idiomatic way to do things, but at least here is the idea.

### CODE REVIEW

**Comment by leoloobeek** [comment]
Apologize for the very late response here, thanks and I'll take a look!

**Comment by capnspacehook** [comment]
This is a really good idea, but the only problem is that you're keying a keyed payload. Meaning there's a binary inside a binary inside a binary. Go binaries are already huge, so the size of the final payload will be yuuuuuge. 

Just thinking out loud here, but a solution that would encrypt the url of the remote server, and reduce payload size significantly, would be to just say prepend the url of the remote server to the encrypted payload, and encrypt that. Then if and only if the first round of keying succeeds, the first layer of encryption will be peeled off, revealing a url followed by more encrypted data. Then you'd take that and try and generate a key from the remote server, and attempt to decrypt the last encrypted layer using that key. Thoughts?

**Comment by leoloobeek** [comment]
First off, thanks for the PR! Happy to see some have found this project useful :)

So, Re:"writing the result file multiple times" -- I may need more details from you on this. The result file is only written out at the very end of the `Run` function [here](https://github.com/leoloobeek/keyring/blob/master/keyring.go#L196).

I decided to disagree with `golint` as I thought `GenerateHttpKey` looked nicer, but now someone has noticed it! I'll agree and change that around :)

Finally on the major topic at hand, some thoughts:
* This would not work with the C# language. I'm not compiling the C# payload and it just outputs the raw source. The C# language encrypts the bytes of a given C# binary and eventually uses `Assembly.Load()` to run it. If it contained the nested C# source code, `Assembly.Load()` would fail. 
* This would indeed work with the other two languages, PowerShell and Jscript, as they're text-based scripting languages. 
* I like @capnspacehook's idea of prepending the remote resource to the rest of the data. This would keep down on size and also allow nesting the keys without too much added size to the entire encrypted blob. This is what I understand the encrypted data layout would be, if successfully decrypted: `[HTTP URL/DNS hostname][encrypted data]`. You could then pull out the HTTP URL or DNS hostname and the rest of the encrypted data and  try HTTP or DNS keying to decrypt the remaining blob. This is probably the best route.
* I will say, we should keep the `disableNesting` flag. For deceptive purposes, I have set an HTTP key that isn't actually used in an attempt to throw off the blue team. I want to continue to have this tool not do "too much" for the user to allow for people to be creative.

Let me know your guys' thoughts here.

**Comment by capnspacehook** [comment]
That sounds good, the only thing I would add is that the user agent used should be prepended after the url but before the encrypted blob.

Also, what do you mean about setting an HTTP key that isn't used? I haven't seen that anywhere

**Comment by leoloobeek** [comment]
In the config file if the `keydata` is blank, it will be included in the final payload but due to how the combinations work, it won't actually be used to encrypt/decrypt the payload. This way, you can appear to be encrypting the data with a variety of different keyers but when looking at the final payload you don't really know what is being used.

This part in the Jscript walkthrough in the Wiki describes it.
https://github.com/leoloobeek/keyring/wiki/Walkthrough:-JScript#adding-a-benign-keyer-function

I mention it a little in my talk around the 14:10 mark.
https://www.youtube.com/watch?v=MHc3XP3XC4I

I've just set the HTTP keydata blank so the payload appears to request data from a page but doesn't actually use it towards the key. Definitely an edge case scenario but still something that is nice to have available.

**Pull request closed without merging**
